### ISSUE TITLE
Nova Questão: Quais os temas preferidos de cada vereador e partido?

### ISSUE THREAD

**Issue by augustoqm** [augustoqm/cg-insights#2]
- [x] Analisar os temas principais de cada vereador (com heatmap por exemplo)
- [ ] Agregar também por partido político

**Comment by augustoqm** [comment]
Analise com heatmap DONE.

**Comment by nazareno** [comment]
Onde está a análise com heatmap, @augustoqm ?

**Comment by augustoqm** [comment]
Oi @nazareno todas as análises que fiz estão aqui:
[https://github.com/augustoqm/cg-insights/tree/master/insights](https://github.com/augustoqm/cg-insights/tree/master/insights)

Pretendo passar elas pra uma github pages (ou podemos adicioná-las no oqfuv), a do heatmpa é a do html, a última, ela não renderiza no github, então baixa e abre. Tá usando o flexdashboards.

**Comment by augustoqm** [comment]
@tacianosilva outra análise que precisamos fazer é agrupando os vereadores por comissão. Elas tem focos bem definidos, acredito que isso é definitivo dos temas dos vereadores.

**Comment by augustoqm** [comment]
Fechando issue com análise dos vereadores apenas. A parte dos temas por partido será tratada em outro post.
