### ISSUE TITLE
Nova Questão: Os vereadores suplentes tem o mesmo fôlego de ementas que os eleitos?

### ISSUE THREAD

**Issue by augustoqm** [augustoqm/cg-insights#5]
Vimos que a quantidade de ementas tende a diminuir com o passar dos anos do mandato. Isso deve-se ao fato de que os suplentes redigem criam menos ementas?
- [x] Buscar informação sobre data de entrada (suplentes) e saída de vereadores da câmara de CG e adicionar no insight [Meu Vereador? Explique-me por favor...](https://github.com/augustoqm/cg-insights/blob/master/insights/vereador_expliqueme.md)

**Comment by tacianosilva** [comment]
@augustoqm ontem estava pensando justamente nisso. Não analisamos as ementas dos vereadores suplentes que eventualmente são empossados quando o vereador eleito assume outro posto no executivo.

**Comment by augustoqm** [comment]
Pois é, esse é um "filtro" que precisamos fazer antes de definir se um vereador trabalhou muito ou pouco.  Primeiro precisamos dos dados de quando os suplentes tomaram os cargos (individualmente). Depois é analisar.

**Comment by augustoqm** [comment]
Adicionei informação no final de [Meu Vereador? Explique-me por favor...](https://github.com/augustoqm/cg-insights/blob/master/insights/vereador_expliqueme.md).
Mas a página vai ser removida e iremos usar essas informações tanto no OQFUV quanto em outro post unindo partidos/coligações com esses manejos Políticos.
