### ISSUE TITLE
Redução do número de temas

### ISSUE THREAD

**Issue by nazareno** [augustoqm/cg-insights#9]
Estou imaginando algo como PCA para entendermos a atuação dos vereadores a partir de poucas dimensões. Alguns testes com os vereadores da legislatura que acaba em 2016 parecem mostrar que 3 CPs explicam 90%+ da variância dos temas originais.

**Comment by nazareno** [comment]
Ué, não posso fazer assign pra mim nem adicionar labels às issues? @augustoqm ?

**Comment by augustoqm** [comment]
Oxe @nazareno, é só pedir. =)
Já mandei lá. Adicionei o time todo tb. 

A ideia é show! Vocês já fizeram isso com os deputados e deu muito certo. Dá também pra os vereadores. Vamos ver, gera a viz e a gente bate com o que esperamos.

**Comment by augustoqm** [comment]
Outra ideia @nazareno é usar o [TSNE](https://lvdmaaten.github.io/tsne/). Já usei e ele é bem interessante, já gera os componentes otimizado para visualização.

**Comment by nazareno** [comment]
A ideia de usar o tSNE e gerar visualização é muito boa também. 
Eu estava ainda no passo anterior. Pensei que era uma boa ter um conjunto pequeno de dimensões que conseguimos explicar. Algo tipo "Causas de minorias", "Serviços urbanos e afins", etc. Aí eu acho que podia ser 3 ou mais. Pra ficarem explicáveis, pensei em PCA.

**Comment by augustoqm** [comment]
Sim @nazareno, entendi! É uma boa, podemos criar mas antes vou olhas as _comissões tecnicas_ pq elas tem focos bem definidos. Vou fazer isso esse fds e iteramos com o resultado.
